=== YIueil/yl-bdf/yl-bdf-web-query/src/main/resources/dynamicsql/yl-dynamic-sql.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.yiueil.cc"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="rootType"/>
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="configType" name="config" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="cache" use="required"/>
  </xs:complexType>
  <xs:complexType name="configType">
    <xs:sequence>
      <xs:element type="xs:string" name="sql"/>
      <xs:element type="paramsType" name="params"/>
      <xs:element type="filtersType" name="filters"/>
      <xs:element type="xs:string" name="endSql"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="description"/>
  </xs:complexType>
  <xs:complexType name="paramType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="default"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="paramsType">
    <xs:sequence>
      <xs:element type="paramType" name="param"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="filterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="left"/>
        <xs:attribute type="xs:string" name="right"/>
        <xs:attribute type="xs:string" name="type"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="filtersType">
    <xs:sequence>
      <xs:element type="filterType" name="filter"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== YIueil/yl-bdf/examples/yl-acc/src/main/resources/dynamicsql/application.xml
<?xml version="1.0" encoding="UTF-8"?>
<root cache="true"
      xmlns="http://www.yiueil.cc"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.yiueil.cc https://yiueil.github.io/static-repo/static/xsd/yl-dynamic-sql.xsd">
    <!--获取管理中的应用-->
    <config id="getManageApplicationList">
        <sql><![CDATA[
            select distinct a.id,
                            a.createtime "createTime",
                            a.createuserid "createUserId",
                            a.description,
                            a.guid,
                            a.modifytime "modifyTime",
                            a.name,
                            a.url
            from yl_acc.application a
                     left join yl_acc.application_manager am on am.applicationid = a.id
            where am.managerid = :userId
        ]]></sql>
        <params>
            <param name="userId"/>
        </params>
        <endSql><![CDATA[
            order by a.createtime
        ]]></endSql>
    </config>

    <!--获取用户应用功能-->
    <config id="getUserApplicationFunctions">
        <sql><![CDATA[
            select f.id,
                   f.applicationid,
                   f.createtime,
                   f.createuserid,
                   f.description,
                   f.guid,
                   f.method,
                   f.modifytime,
                   f.name,
                   f.parentid,
                   f.type,
                   f.url,
                   f.rightname
            from yl_acc.function f
                     left join yl_acc.role_function rf on rf.functionid = f.id
                     left join yl_acc.user_role ur on ur.roleid = rf.roleid
            where f.applicationid = :applicationId
              and ur.userid = :userId
        ]]></sql>
        <params>
            <param name="userId"/>
            <param name="applicationId"/>
        </params>
        <endSql><![CDATA[
            order by f.createtime desc
        ]]></endSql>
    </config>

    <!--获取应用列表-->
    <config id="getApplicationList">
        <sql><![CDATA[
            select app.id, app.guid, app.name, app.iconurl as "iconUrl", app.description, app.status, app.url, string_agg(u.username, ',') as "applicationManager"
            from yl_acc.application app
                     left join yl_acc.application_manager appm on appm.applicationid = app.id
                     left join yl_acc."user" u on u.id = appm.managerid
            where 1 = 1
        ]]></sql>
        <filters>
            <filter name="filterString" left="%" right="%"><![CDATA[
                and app.name like :filterString
            ]]></filter>
            <filter name="status"><![CDATA[
                and app.status = :status
            ]]></filter>
        </filters>
        <endSql><![CDATA[
            group by app.id, app.guid, app.name, app.iconurl, app.description, app.status, app.url
            order by app.id desc
        ]]></endSql>
    </config>
</root>

=== YIueil/yl-bdf/yl-bdf-query/yl-bdf-web-query/src/main/resources/dynamicsql/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--使用dtd约束-->
<!--<!DOCTYPE root PUBLIC "yl-dynamic-sql.xsd" "https://yiueil.github.io/static-repo/static/dtd/yl-dynamic-sql.dtd">-->

<!--是应用xsd约束-->
<root cache="true"
      xmlns="http://www.yiueil.cc"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.yiueil.cc https://yiueil.github.io/static-repo/static/xsd/yl-dynamic-sql.xsd">
    <config id="exampleConfig">
        <sql><![CDATA[
            select * from table where 1 = 1 and id in (:ids)
        ]]></sql>
        <params>
            <param name="ids"/>
        </params>
        <filters>
            <filter name="guid" left="" right=""><![CDATA[
                and guid = :guid
            ]]></filter>
        </filters>
        <endSql><![CDATA[
            order by id desc
        ]]></endSql>
    </config>
</root>
